version: "3.9"
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: kutuphane
      POSTGRES_USER: canatalay
      POSTGRES_PASSWORD: canatalay.374
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build: .
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql+psycopg2://canatalay:canatalay.374@db:5432/kutuphane
    ports:
      - "8080:8080"
    command: python uygulama.py

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - db

volumes:
  pgdata:
